name: Test ft_ping

on:
  push:
    branches: [ "main", "ralf", "jakub" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
#     - name: make check
#       run: make check
    - name: dry-run
      run: ./ft_ping
